### ISSUE TITLE
Build docs.rs with all features

### ISSUE THREAD

**Issue by jeffa5** [alexjg/autosurgeon#10]
The docs mention that an implementation for `uuid` is provided behind a feature flag. It would be more discoverable if this was reflected as a documented type, and so searchable.

**Comment by alexjg** [comment]
Do you mean adding something like this to `Cargo.toml`

```toml
[package.metadata.docs.rs]
all-features = true
```

Or is there more that would need to be done?
